import React from 'react';
import book from '../assets/Its-About-Time-Book.png';
import timeEternity from '../assets/Small-Image-.png';
import buyBook from '../assets/Davids-Audible-popup-small3.jpg';
export default function Home() {
	return (
		<main className='pt-10'>
			<div className='flex mx-auto'>
				<div className='ml-10'>
					<h1 className='text-7xl inline'>Its About Time</h1>
					<h4 className='text-2xl italic'>Science Harmonized with Religion</h4>
				</div>
			</div>
			<div className='flex items-center text-lg'>
				<div className='flex flex-col  w-1/2'>
					<div className='mt-10'>
						<div className='w-3/4 mx-auto mb-5'>
							If science is true and religion is true, must they not harmonize? Two truths cannot contradict one another. As Galileo said, “All truths are easy to understand once they are discovered;
							the point is to discover them.”
						</div>
						<div className='w-3/4 mx-auto mb-5'>
							What is time has been a puzzle for philosophers and scientists throughout the ages. We know that time as generated by man has contributed enormously to our high-tech society – providing
							such things as GPS, cell-tower synchronization for cell phones, and an enormous number of other benefits. But do they use time? They use time interval. A calendar measures time since the
							birth of Christ. The typical watch measures time since noon or midnight, etc.
						</div>
						<div className='w-3/4 mx-auto mb-5'>
							If we can “discover” God’s timing, will it bring true science and true religion into harmony? Will it give you a strong connection between things spiritual, scientific, physical,
							emotional, political, historical and mental? Will it help bring peace on earth and good will among men?
						</div>
						<div className='w-3/4 mx-auto mb-5'>
							In God’s timing, is now the most exciting time in the history of the Earth? David Allan desires to share with you answers to these profound questions. It’s About Time to harmonize true
							science and true religion with enormous benefits for you and a world in need of this vital message! You will be amazed at the answers and value you will find in his book.
						</div>
					</div>
				</div>
				<div className='flex flex-col w-1/2'>
					<div className='flex'>
						<img
							className='h-[200px] lg:h-[400px]'
							src={book}
							alt='book'
						/>
						<ul className='text-left ml-4'>
							<li className='mb-6'>Is God’s Time the ultimate in knowing what life is about?</li>
							<li className='mb-6'>Is man’s time different from God’s time?</li>
							<li className='mb-6'>Where are we in God’s Time?</li>
							<li className='mb-6'>Am I a child of God or am I evulved?</li>
							<li className='mb-6'>Is there science behind my prayer channel to God?</li>
							<li className='mb-6'>How does understanding time help me to know who I am and find meaning in life?</li>
						</ul>
					</div>
					<div className='mt-5'>
						<div className='mb-2 italic'>
							After that experience of receiving direct guidance [in master’s thesis, aka “Allan variance”], I knew that the Lord can and will bless us in all that we do as we seek for light and Truth
							and to do His will. Further, it doesn’t matter whether it is in religious activities or school or family or work or wherever.
						</div>
						<div className='mb-2 italic'>
							After that experience, I sought Him at every opportunity and that has made a great difference in my life. Also, I learned that if we seek not for self-aggrandizement but to serve and use
							our talents, as my wise BYU physics professor counseled me that makes a big difference as well.
						</div>

						<div className='mb-2 italic'>
							I believe that the Truths of God will harmonize in all areas of life if we will but try to understand the Truth from Him, who is the author of all Truth, and live in harmony with those
							Truths to the best of our abilities once we receive them. I believe God is the Master Physicist along with being the Master of the Universe.
						</div>
					</div>
				</div>
			</div>
			<div className='w-full flex flex-wrap justify-evenly mt-7 border-t-2 border-b-2 py-8'>
				<div
					className='flex flex-col items-center bg-olive-500 hover:bg-olive-600 w-1/4 rounded-md p-4 cursor-pointer'
					onClick={() => {
						window.open('https://www.digitalegend.com/products/time-and-eternity-end-times-and-beyond-revealed');
					}}
				>
					Buy the book Time and Eternity for some information about this book here. Probably that is only a couple of sentences
					<img
						className='h-[180px]'
						src={timeEternity}
						alt='time and eternity book'
					/>
				</div>
				<div
					className='flex flex-col items-center bg-olive-500 hover:bg-olive-600 w-1/4 rounded-md p-4 cursor-pointer'
					onClick={() => {
						window.open('http://www.amazon.com/exec/obidos/ASIN/1937735753/pureenergysys-20');
					}}
				>
					Buy the book It's About Time for some information about this book here. Probably that is only a couple of sentences
					<img
						className='h-[180px]'
						src={book}
						alt='Its about time book'
					/>
				</div>
				<div
					className='flex flex-col items-center bg-olive-500 hover:bg-olive-600 w-1/4 rounded-md p-4 cursor-pointer'
					onClick={() => {
						window.open('https://www.audible.com/pd/Religion-Spirituality/Its-About-Time-Science-Harmonized-with-Religion-Audiobook/B071RW2QS9?http://');
					}}
				>
					Buy the audio It's About Time for some information about this book here. Probably that is only a couple of sentences
					<img
						className='h-[180px]'
						src={buyBook}
						alt='Its about time itunes'
					/>
				</div>
			</div>
			{/* <hr className='my-5 border-dashed border-2 border-b-jet-500' /> */}
			<div className='w-3/4 mx-auto mt-10 p-4'>
				<h1 className='text-4xl mb-4'>Reviews</h1>
				<div className='text-2xl mb-4 italic border-2 border-jet-100 rounded-md p-4'>
					<div>
						<span className='mr-2'>Amazon Review</span>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
					</div>
					I feel like the author's motivation for writing it was love of God, love of people and desire for truth in connecting all things. It interesting and inspiring.
				</div>
				<div className='text-2xl mb-4 italic border-2 border-jet-100 rounded-md p-4'>
					<div>
						<span className='mr-2'>Amazon Review</span>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
					</div>
					Excellent book written by an expert in the field of time studies.
				</div>
				<div className='text-2xl mb-4 italic border-2 border-jet-100 rounded-md p-4'>
					<div>
						<span className='mr-2'>Amazon Review</span>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
						<i class='fa-solid fa-star text-yellow-300'></i>
					</div>
					A fascinating amalgamation of scientific theory and divine revelation.
				</div>
			</div>
		</main>
	);
}
